name: Create custom release

env:
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:
  pull_request:

jobs:
  build_android_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-linux-android
          override: true
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: android-actions/setup-android@v3
        with:
          packages: "platforms;android-32"
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26b

      - name: Build and package ALVR
        id: build
        env:
          RUST_BACKTRACE: 1
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: cargo xtask package-client --ci

      #- name: Sign APK
      #  uses: ilharp/sign-android-release@v1
      #id: sign_apk
      #with:
      #releaseDir: build/alvr_client_android
      #signingKey: ${{ secrets.SIGNING_KEY }}
      #keyAlias: ${{ secrets.KEY_ALIAS }}
      #keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      #keyPassword: ${{ secrets.KEY_PASSWORD }}
      #buildToolsVersion: 34.0.0

      - name: Upload APK
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: build/alvr_client_android
